import { Profile } from "@/components/home/MatchCard";
const DUMMY = require("../../assets/images/demo_post.png");

export const MOCK_PROFILES: Profile[] = [
  { id: "1", name: "Priya", age: 21, gender: "Female", distance: "18 km away", distanceNum: 18, liked: true, recentlyActive: false, religion: "Hindu", location: "Kolkata", match: 75, interests: ["Hiking","Gaming","Coffee","Meditation","Photography"], main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], verified: true, occupation: "Designer", tagline: "Just looking for someone to share hiking and gaming with", about: "Hi, I'm Priya — passionate about design and always exploring new things. Let's talk about coffee and see where it goes!", height: "5'4\"", zodiac: "Scorpio", education: "B.Tech, NIT", preferences: ["Non-smoker", "Dog lover", "Vegetarian"] },
  { id: "2", name: "Ananya", age: 28, gender: "Female", distance: "16 km away", distanceNum: 16, liked: true, recentlyActive: false, religion: "Muslim", location: "Mumbai", match: 91, interests: ["Hiking","Music","Cooking","Art","Dance"], main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], verified: true, occupation: "Photographer", tagline: "Just looking for someone to share hiking and music with", about: "Hi, I'm Ananya — I love capturing moments behind the lens and cooking for the people I care about.", height: "5'2\"", zodiac: "Scorpio", education: "B.Tech, NIT", preferences: ["Non-smoker", "Dog lover", "Vegetarian"] },
  { id: "3", name: "Meera", age: 28, gender: "Female", distance: "1 km away", distanceNum: 1, liked: true, recentlyActive: true, religion: "Sikh", location: "Mumbai", match: 94, interests: ["Dance","Hiking","Music","Photography","Cooking"], main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], verified: true, occupation: "Photographer", tagline: "Just looking for someone to share dance and hiking with", about: "Hi, I'm Meera — dance and music are my language. Let's find our rhythm together.", height: "5'4\"", zodiac: "Scorpio", education: "B.Tech, NIT", preferences: ["Non-smoker", "Dog lover", "Vegetarian"] },
  { id: "m1", name: "Priya", age: 24, gender: "Female", distance: "2 km away", match: 92, main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], interests: ["Travel","Books","Photography"], height: "165cm", location: "Delhi", about: "Travel enthusiast and avid reader. Always up for a good conversation over coffee.", occupation: "Content Writer", zodiac: "Libra", education: "BA English", preferences: ["Non-smoker", "Pet lover"] },
  { id: "m2", name: "Ananya", age: 26, gender: "Female", distance: "5 km away", match: 87, main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], interests: ["Books","Music","Art"], height: "170cm", location: "Mumbai", about: "Lost in books, found in music. Looking for someone who loves weekend art galleries.", occupation: "Graphic Designer", zodiac: "Virgo", education: "BFA", preferences: ["Non-smoker", "Vegetarian"] },
  { id: "m3", name: "Kavya", age: 25, gender: "Female", distance: "10 km away", match: 94, main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], interests: ["Art","Cooking","Yoga"], height: "160cm", location: "Bangalore", about: "Artist by day, home chef by night. My happy place is the kitchen or the studio.", occupation: "Artist", zodiac: "Cancer", education: "M.Sc Fine Arts", preferences: ["Non-smoker", "Vegetarian"] },
  { id: "m4", name: "Meera", age: 23, gender: "Female", distance: "12 km away", match: 79, main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], interests: ["Music","Dance","Fitness"], height: "168cm", location: "Pune", about: "Music is my medicine, dance is my therapy. I live for live concerts.", occupation: "Music Teacher", zodiac: "Aries", education: "B.Mus", preferences: ["Non-smoker"] },
  { id: "m5", name: "Shreya", age: 27, gender: "Female", distance: "15 km away", match: 81, main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], interests: ["Dance","Travel","Photography"], height: "162cm", location: "Chennai", about: "Bharatanatyam dancer who loves capturing stories through a lens. Wanderlust is real.", occupation: "Dance Instructor", zodiac: "Gemini", education: "MA Dance", preferences: ["Non-smoker", "Vegetarian"] },
  { id: "m6", name: "Nisha", age: 22, gender: "Female", distance: "20 km away", match: 88, main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], interests: ["Cooking","Fitness","Meditation"], height: "155cm", location: "Hyderabad", about: "Fitness enthusiast and aspiring chef. Balance is my lifestyle — gym in the morning, kitchen in the evening.", occupation: "Nutritionist", zodiac: "Taurus", education: "B.Sc Nutrition", preferences: ["Non-smoker", "Vegetarian"] },
  { id: "l1", name: "Riya", age: 24, gender: "Female", distance: "3 km away", match: 90, main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], interests: ["Fitness","Hiking","Coffee"], height: "165cm", location: "Delhi", liked: true, about: "Fitness junkie equally passionate about strong coffee and mountain trails.", occupation: "Personal Trainer", zodiac: "Leo", education: "B.PE", preferences: ["Non-smoker", "Dog lover"] },
  { id: "l2", name: "Sneha", age: 25, gender: "Female", distance: "7 km away", match: 85, main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], interests: ["Yoga","Meditation","Travel"], height: "170cm", location: "Mumbai", liked: true, about: "Yoga teacher and mindfulness enthusiast. I believe in slow living and meaningful connections.", occupation: "Yoga Instructor", zodiac: "Pisces", education: "Yoga Teacher Training", preferences: ["Non-smoker", "Vegetarian"] },
  { id: "l3", name: "Pooja", age: 23, gender: "Female", distance: "11 km away", match: 93, main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], interests: ["Gaming","Movies","Art"], height: "160cm", location: "Bangalore", liked: true, about: "Game developer who loves old films and weekend sketching sessions. Nerd in the best way.", occupation: "Game Developer", zodiac: "Scorpio", education: "B.Tech CS", preferences: ["Non-smoker"] },
  { id: "l4", name: "Divya", age: 26, gender: "Female", distance: "14 km away", match: 78, main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], interests: ["Hiking","Photography","Coffee"], height: "168cm", location: "Pune", liked: true, about: "Weekend hiker who photographs everything she sees. Coffee first, then everything else.", occupation: "UX Designer", zodiac: "Capricorn", education: "B.Des", preferences: ["Non-smoker", "Dog lover"] },
  { id: "l5", name: "Isha", age: 22, gender: "Female", distance: "18 km away", match: 80, main_photo: DUMMY, photos: [DUMMY, DUMMY, DUMMY], interests: ["Photography","Dance","Music"], height: "162cm", location: "Chennai", liked: true, about: "Portrait photographer and Carnatic music lover. I find stories in faces and rhythms in everyday life.", occupation: "Photographer", zodiac: "Sagittarius", education: "BFA Photography", preferences: ["Non-smoker", "Vegetarian"] },
];
