services:
  postgres:
    image: postgres:16
    container_name: dating_postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dating_platform

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - dating_network

  redis:
    image: redis:7
    container_name: dating_redis
    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - dating_network

volumes:
  postgres_data:
  redis_data:

networks:
  dating_network: